export { default as Home } from './Home'
export { default as MyToken } from './MyToken'
export { default as Swap } from './Swap'
export { default as Staking } from './Staking'
export { default as DashBoard } from './DashBoard'
export { default as NotFound } from './NotFound'
export { default as Transfer } from './Transfer'